import type { Section, Band } from "./types";

export const SECTIONS_FALLBACK: Section[] = [
  {
    id: "S1", label_it: "Catena di Fornitura Digitale", label_en: "Digital Supply Chain",
    weight_pct: 20, framework: "NIS2",
    questions: [
      { id: "S1Q1", weight: 30, threshold: 50,
        text: "La struttura ha censito tutti i fornitori software che accedono o trattano dati clinici degli ospiti?",
        sublabel: "Gestionale clinico, cartella elettronica, telemedicina, piattaforme cloud per referti",
        normativa: "Art. 21 D.Lgs. 138/2024 — Art. 28 GDPR",
        labels: ["Nessun censimento effettuato", "Censimento parziale, molti fornitori ignoti", "Elenco incompleto o non aggiornato", "Censimento completo, valutazione sicurezza assente", "Registro completo con valutazione sicurezza per ogni fornitore"] },
      { id: "S1Q2", weight: 25, threshold: 50,
        text: "Con ogni fornitore che tratta dati clinici è stato stipulato un contratto DPA conforme GDPR?",
        sublabel: "Data Processing Agreement — obbligatorio per ogni soggetto esterno che tratta dati per conto della struttura",
        normativa: "Art. 28 GDPR",
        labels: ["Nessun DPA con alcun fornitore", "DPA solo con il fornitore principale", "DPA con la maggior parte, alcuni mancanti", "DPA con tutti, ma non aggiornati", "DPA aggiornati e firmati con tutti i fornitori"] },
      { id: "S1Q3", weight: 20, threshold: 50,
        text: "I fornitori cloud/software sono stati valutati per la localizzazione dei dati e il rispetto GDPR per trasferimenti extra-UE?",
        sublabel: "Server in USA, UK o paesi terzi richiedono Standard Contractual Clauses o decisioni di adeguatezza",
        normativa: "Art. 44-49 GDPR — Schrems II",
        labels: ["Non so dove risiedono i dati degli ospiti", "Dati in UE senza documentazione formale", "Dati in UE verificati, trasferimenti extra-UE non gestiti", "Tutti i trasferimenti documentati con SCC", "Data residency verificata, SCC aggiornate, audit annuale"] },
      { id: "S1Q4", weight: 25, threshold: 50,
        text: "In caso di incidente o interruzione di un fornitore critico, la struttura ha un piano di continuità operativa documentato?",
        sublabel: "Business Continuity Plan per gestionale offline, procedure di backup, contatti di emergenza",
        normativa: "Art. 21 par. 2 lett. c D.Lgs. 138/2024",
        labels: ["Nessun piano — non sappiamo come procedere", "Procedure informali non documentate", "Piano esistente ma non testato né aggiornato", "Piano documentato, test occasionali", "BCP documentato, testato annualmente, personale formato"] },
    ],
  },
  {
    id: "S2", label_it: "Sistemi AI e Dispositivi Medici", label_en: "AI Systems & Medical Devices",
    weight_pct: 25, framework: "AI Act",
    questions: [
      { id: "S2Q1", weight: 30, threshold: 25,
        text: "La struttura utilizza sistemi algoritmici o AI per supportare decisioni cliniche o monitorare gli ospiti?",
        sublabel: "Rilevamento cadute, deterioramento cognitivo, gestione terapia, score di fragilità, monitoraggio parametri vitali automatizzato",
        normativa: "Art. 6 + Allegato III punto 5(b) AI Act — MDR 2017/745",
        labels: ["Nessun sistema AI in uso", "Uso sperimentale occasionale, non integrato", "Sistemi AI integrati, non classificati né valutati", "Classificazione effettuata, FRIA in corso", "Classificati, FRIA completata, Dossier Tecnico acquisito"] },
      { id: "S2Q2", weight: 25, threshold: 50,
        text: "Per ogni sistema AI in uso clinico, è stata verificata la conformità AI Act del fornitore (certificazione, Dossier Tecnico)?",
        sublabel: "Il deployer (la struttura) è corresponsabile se usa un sistema non conforme dopo agosto 2026",
        normativa: "Art. 26 AI Act — Obblighi deployer",
        labels: ["Non abbiamo verificato la conformità di nessun fornitore", "Richieste inviate, nessuna documentazione ricevuta", "Documentazione parziale da alcuni fornitori", "Documentazione ricevuta dalla maggior parte", "Dossier Tecnico e dichiarazione di conformità per ogni sistema AI"] },
      { id: "S2Q3", weight: 20, threshold: 50,
        text: "Il personale clinico che usa sistemi AI ha ricevuto formazione specifica sull'uso, i limiti e i rischi di questi strumenti?",
        sublabel: "L'AI Act Art. 4 introduce l'obbligo di AI literacy per tutto il personale che usa sistemi AI",
        normativa: "Art. 4 AI Act — Art. 26 par. 6",
        labels: ["Nessuna formazione AI erogata", "Formazione informale dal fornitore all'installazione", "Formazione base erogata, non documentata", "Formazione documentata, aggiornamento pianificato", "Piano formativo strutturato, documentato, con verifica periodica"] },
      { id: "S2Q4", weight: 15, threshold: 50,
        text: "La struttura ha effettuato una DPIA per i sistemi AI che trattano dati sanitari degli ospiti?",
        sublabel: "Obbligatoria per trattamenti sistematici di dati sanitari — combinazione AI + dati clinici è sempre ad alto rischio GDPR",
        normativa: "Art. 35 GDPR — EDPB WP248",
        labels: ["Nessuna DPIA effettuata per alcun sistema", "DPIA solo per il gestionale principale", "DPIA in corso per i sistemi principali", "DPIA completate per la maggior parte dei sistemi", "DPIA complete per tutti i sistemi, revisione annuale"] },
      { id: "S2Q5", weight: 10, threshold: 50,
        text: "I software clinici in uso sono stati verificati per una eventuale classificazione come dispositivo medico (MDR)?",
        sublabel: "Software che elabora dati clinici per supportare diagnosi o terapia può essere Classe IIa o superiore",
        normativa: "Art. 2 MDR 2017/745 — MDCG 2019-11",
        labels: ["Non abbiamo mai verificato la classificazione MDR", "Il fornitore ha dichiarato non-MD, senza documentazione", "Verifica per alcuni software, documentazione parziale", "Classificazione MDR verificata per i software principali", "Classificazione documentata per tutti i software clinici"] },
    ],
  },
  {
    id: "S3", label_it: "Shadow IT e Governo dei Dati", label_en: "Shadow IT & Data Governance",
    weight_pct: 20, framework: "D.Lgs. 231",
    questions: [
      { id: "S3Q1", weight: 30, threshold: 50,
        text: "Il personale utilizza dispositivi personali (BYOD) per accedere a dati clinici degli ospiti o comunicare informazioni sanitarie?",
        sublabel: "Smartphone personali per foto ospiti, tablet privati per il gestionale, email personali per referti",
        normativa: "Art. 24-bis D.Lgs. 231/2001 — L. 132/2025 — Art. 32 GDPR",
        labels: ["Uso sistematico non regolamentato di dispositivi personali", "Uso frequente tollerato informalmente", "Policy BYOD esistente ma non applicata", "Policy attiva, formazione erogata, controlli occasionali", "BYOD vietato o con MDM, policy firmata da ogni dipendente"] },
      { id: "S3Q2", weight: 35, threshold: 50,
        text: "Il personale utilizza strumenti AI generativa non autorizzati (ChatGPT, Claude consumer, Gemini) per redigere documentazione clinica?",
        sublabel: "Note cliniche, diari infermieristici, relazioni scritte con AI consumer che inviano dati a server esteri",
        normativa: "Art. 24-bis D.Lgs. 231/2001 — L. 132/2025 — Art. 9+32 GDPR",
        labels: ["Uso diffuso e non regolamentato per documenti clinici", "Uso noto alla direzione, non affrontato formalmente", "Divieto verbale, nessuna policy né controllo", "AI Use Policy adottata, formazione in corso", "AI Use Policy firmata da tutti, strumenti approvati, audit periodici"] },
      { id: "S3Q3", weight: 20, threshold: 50,
        text: "La struttura utilizza app di messaggistica consumer (WhatsApp, Telegram) per comunicazioni cliniche tra operatori o con famiglie?",
        sublabel: "Dati sanitari, foto ospiti, aggiornamenti clinici via canali non conformi GDPR",
        normativa: "Art. 32 GDPR — Provvedimento Garante WhatsApp in ambito sanitario 2024",
        labels: ["WhatsApp usato sistematicamente per comunicazioni cliniche", "Uso frequente tollerato, nessuna alternativa aziendale", "Strumenti aziendali disponibili ma non sempre usati", "Policy adottata, strumenti sicuri forniti", "Solo strumenti aziendali cifrati approvati, nessun dato clinico su consumer"] },
      { id: "S3Q4", weight: 15, threshold: 50,
        text: "Esiste un sistema di logging e controllo accessi ai sistemi clinici che traccia chi ha acceduto a quali dati e quando?",
        sublabel: "Audit trail accessi gestionale, log autenticazioni, alert su accessi anomali — obbligatorio per accountability GDPR",
        normativa: "Art. 5 par. 2 + Art. 32 GDPR — Art. 21 D.Lgs. 138/2024",
        labels: ["Nessun log accessi clinici", "Log solo del sistema principale, non analizzati", "Log attivi, revisione occasionale", "Log centralizzati, revisione periodica, alert configurati", "SIEM attivo, log centralizzati, analisi automatica anomalie, retention documentata"] },
    ],
  },
  {
    id: "S4", label_it: "Gestione Incidenti e Notifiche", label_en: "Incident Management & Notifications",
    weight_pct: 15, framework: "NIS2",
    questions: [
      { id: "S4Q1", weight: 35, threshold: 50,
        text: "La struttura dispone di una procedura documentata per rilevare, classificare e rispondere a incidenti di sicurezza informatica?",
        sublabel: "Incident Response Plan — obbligatorio per soggetti NIS2: chi fa cosa, entro quanto, con quali strumenti",
        normativa: "Art. 21 par. 2 lett. b D.Lgs. 138/2024",
        labels: ["Nessuna procedura — gestiamo gli incidenti caso per caso", "Procedure informali note solo all'IT", "Procedura esiste ma non è stata testata", "IRP documentato, test annuale, personale informato", "IRP documentato, testato semestralmente, esercitazioni, revisione post-incidente"] },
      { id: "S4Q2", weight: 35, threshold: 25,
        text: "In caso di incidente significativo, la struttura è in grado di notificare all'ACN entro 72 ore come previsto da NIS2?",
        sublabel: "Obbligo di notifica entro 72h per soggetti essenziali/importanti — la nuova tassonomia ACN (maggio 2026) definisce cosa notificare",
        normativa: "Art. 25 D.Lgs. 138/2024 — Tassonomia CSIRT Italia 2026",
        labels: ["Non sappiamo come notificare ad ACN", "Conosciamo l'obbligo, nessuna procedura attiva", "Procedura di notifica abbozzata, non testata", "Procedura attiva, referente designato, contatti ACN noti", "Procedura testata, canale ACN attivo, notifica entro 24h garantita"] },
      { id: "S4Q3", weight: 30, threshold: 50,
        text: "La struttura ha implementato misure di backup e ripristino che garantiscano la continuità delle cure in caso di attacco ransomware?",
        sublabel: "Backup isolati (air-gapped), RTO/RPO definiti, test di ripristino — fondamentale per strutture sanitarie",
        normativa: "Art. 21 par. 2 lett. c D.Lgs. 138/2024 — ENISA Healthcare Guidelines",
        labels: ["Nessun sistema di backup strutturato", "Backup locali non isolati, mai testati", "Backup remoti, test occasionali", "Backup isolati con test semestrali, RTO definito", "Backup air-gapped, test mensili, RTO<4h documentato, piano DRP completo"] },
    ],
  },
  {
    id: "S5", label_it: "Formazione e Modello Organizzativo", label_en: "Training & Organizational Model",
    weight_pct: 10, framework: "D.Lgs. 231",
    questions: [
      { id: "S5Q1", weight: 40, threshold: 50,
        text: "Il personale ha ricevuto formazione specifica su cybersicurezza e protezione dei dati negli ultimi 12 mesi?",
        sublabel: "Phishing, password sicure, uso corretto dei gestionali, GDPR base — obbligatoria per esimente D.Lgs. 231",
        normativa: "Art. 6 D.Lgs. 231/2001 — Art. 4 AI Act — Art. 39 GDPR",
        labels: ["Nessuna formazione specifica negli ultimi 12 mesi", "Formazione generica privacy all'assunzione, nulla di recente", "Formazione annuale erogata solo a parte del personale", "Formazione annuale completa, attestati raccolti", "Piano formativo per ruolo, test apprendimento, aggiornamento garantito"] },
      { id: "S5Q2", weight: 30, threshold: 25,
        text: "La struttura ha designato formalmente un DPO (Data Protection Officer) con funzioni operative?",
        sublabel: "Obbligatorio per tutte le strutture sanitarie — non può essere il responsabile qualità né il responsabile IT",
        normativa: "Art. 37-39 GDPR",
        labels: ["Nessun DPO designato", "DPO nominato senza attività operative documentate", "DPO operativo con conflitti di interesse o carico insufficiente", "DPO operativo, indipendente, piano di attività annuale", "DPO operativo, indipendente, accesso diretto al vertice, comunicato al Garante"] },
      { id: "S5Q3", weight: 30, threshold: 50,
        text: "Il Consiglio di Amministrazione ha formalmente approvato e supervisionato le politiche di cybersicurezza?",
        sublabel: "NIS2 Art. 24 impone approvazione e supervisione CdA — mancata approvazione è fattore aggravante in caso di sanzione",
        normativa: "Art. 24 D.Lgs. 138/2024 — Art. 6 D.Lgs. 231/2001",
        labels: ["Il CdA non ha mai discusso cybersicurezza o privacy", "Aggiornamenti informali al CdA, nessuna delibera", "Una delibera generica senza piano specifico", "Delibera CdA con piano approvato, aggiornamento periodico", "Delibera CdA con piano dettagliato, budget dedicato, report trimestrale"] },
    ],
  },
  {
    id: "S6", label_it: "Compliance Regionale e Accreditamento", label_en: "Regional Compliance & Accreditation",
    weight_pct: 10, framework: "DM 77/2022",
    questions: [
      { id: "S6Q1", weight: 35, threshold: 50,
        text: "La struttura ha verificato i requisiti di interoperabilità con il Fascicolo Sanitario Elettronico 2.0 nella propria regione?",
        sublabel: "DM 77/2022 impone integrazione FSE per strutture convenzionate SSN/SSR — termini variano per regione",
        normativa: "Art. 4 DM 77/2022 — DPCM 07/09/2023",
        labels: ["Non abbiamo verificato i requisiti FSE applicabili", "Sappiamo degli obblighi FSE, nessuna azione avviata", "Verifica in corso, fornitore informato, nessuna integrazione", "Integrazione FSE avviata, in fase di test", "Integrazione FSE completata e certificata dalla regione"] },
      { id: "S6Q2", weight: 35, threshold: 50,
        text: "La struttura è coperta da polizza RC Sanitaria conforme al DM 232/2023 (Legge Gelli)?",
        sublabel: "Obbligo per tutte le strutture sociosanitarie — la gestione digitale incide sul profilo di rischio assicurativo",
        normativa: "Art. 10 L. 24/2017 (Legge Gelli) — DM 232/2023",
        labels: ["Nessuna polizza RC sanitaria specifica o copertura inadeguata", "Polizza presente ma non aggiornata al DM 232/2023", "Polizza in aggiornamento, verifica con broker in corso", "Polizza aggiornata, massimali verificati, clausole digitali", "Polizza DM 232/2023 conforme, revisione annuale, copertura cyber verificata"] },
      { id: "S6Q3", weight: 30, threshold: 50,
        text: "I requisiti tecnologici del decreto di accreditamento regionale della struttura sono stati verificati e soddisfatti?",
        sublabel: "Ogni regione ha requisiti tecnici specifici per tipo di struttura — aggiornamenti normativi modificano i requisiti",
        normativa: "DGR regionali specifiche per tipo struttura",
        labels: ["Non conosciamo i requisiti tecnologici del nostro accreditamento", "Conosciamo i requisiti, non abbiamo verificato la conformità", "Verifica parziale, alcune non conformità identificate", "Verifica completa, piano di adeguamento in corso", "Conformità verificata e documentata, piano di mantenimento attivo"] },
    ],
  },
];

// ─── UDO_GROUPS — SSOT per gruppi tipologia struttura
export const UDO_GROUPS: Record<string, string[]> = {
  ANZIANI: [
    "RSA — Residenza Sanitaria Assistenziale",
    "RSSA — Residenza Sanitaria e Socio-Assistenziale",
    "CDI — Centro Diurno Integrato",
    "Hospice — Cure Palliative",
    "OdC — Ospedale di Comunità",
  ],
  SENIOR_LIVING: [
    "SL — Senior Living",
  ],
  DISABILITA: [
    "RSD — Residenza Sanitaria Disabili",
    "CSS — Comunità Socio-Sanitaria (disabili)",
    "CDD — Centro Diurno Disabili",
    "CSE — Centro Socio Educativo",
    "Comunità Alloggio Disabili",
  ],
  PSICHIATRIA: [
    "CRA — Comunità Riabilitativa Alta intensità (psichiatria)",
    "CRM — Comunità Riabilitativa Media intensità (psichiatria)",
    "SRP — Struttura Residenziale Psichiatrica",
    "CPS — Centro Psicosociale",
    "SPDC — Servizio Psichiatrico Diagnosi e Cura",
  ],
  REMS: [
    "REMS — Residenza Esecuzione Misure di Sicurezza",
  ],
  DIPENDENZE: [
    "SerD — Servizio Dipendenze",
    "CT — Comunità Terapeutica (dipendenze)",
  ],
  MINORI: [
    "Comunità Educativa Minori",
    "Casa Famiglia",
  ],
  TERRITORIALE: [
    "ADI — Assistenza Domiciliare Integrata",
    "Poliambulatorio / Centro Riabilitativo ex art.26",
  ],
};

export const S6_WEIGHT_OVERRIDE: Record<string, number> = {
  PSICHIATRIA: 15, REMS: 20, DIPENDENZE: 15, MINORI: 15,
  SENIOR_LIVING: 8, // SL ha minor peso accreditamento regionale SSN
};

export const BANDS: Band[] = [
  { min: 75, label: "RISCHIO CRITICO",   color: "#DC2626", border: "#7F1D1D", bg: "#DC262610" },
  { min: 50, label: "RISCHIO ALTO",      color: "#EA580C", border: "#7C2D12", bg: "#EA580C10" },
  { min: 25, label: "RISCHIO MEDIO",     color: "#CA8A04", border: "#713F12", bg: "#CA8A0410" },
  { min: 0,  label: "RISCHIO CONTENUTO", color: "#16A34A", border: "#14532D", bg: "#16A34A10" },
];

// ─── UDO_OPTIONS — derivato da UDO_GROUPS (SSOT unico)
// Ordine: Anziani → Senior Living → Disabilità → Psichiatria → REMS → Dipendenze → Minori → Territoriale → Altro
export const UDO_OPTIONS: string[] = [
  ...UDO_GROUPS.ANZIANI,
  ...UDO_GROUPS.SENIOR_LIVING,
  ...UDO_GROUPS.DISABILITA,
  ...UDO_GROUPS.PSICHIATRIA,
  ...UDO_GROUPS.REMS,
  ...UDO_GROUPS.DIPENDENZE,
  ...UDO_GROUPS.MINORI,
  ...UDO_GROUPS.TERRITORIALE,
  "Altro",
];
